version: '2'
services:
  master:
    image: $IMAGE
    ports:
      - 5557-5558:5557-5558
      - 8089:8089
    volumes:
      - $LOCUST_DIR:/opt
    environment:
      - ROLE=master
      - TARGET_HOST=$TARGET_HOST
      - LOCUST_FILE=$LOCUST_FILE
  slave:
    image: $IMAGE
    depends_on:
      - master
    network_mode: "service:master"
    volumes:
      - $LOCUST_DIR:/opt
    environment:
      - ROLE=slave
      - MASTER_HOST=master
      - TARGET_HOST=$TARGET_HOST
      - LOCUST_FILE=$LOCUST_FILE
      - SLAVE_MUL=$SLAVE_NUM
      - OAUTH=$OAUTH
      - TOKEN_URL=$TOKEN_URL
      - OAUTH_SCOPE=$OAUTH_SCOPE
  controller:
    image: $IMAGE
    container_name: docker_locusts_controller
    depends_on:
      - master
    network_mode: "service:master"
    environment:
      - ROLE=controller
      - MASTER_HOST=master
      - AUTOMATIC=$AUTOMATIC
      - USERS=$USERS
      - HATCH_RATE=$HATCH_RATE
      - SLAVE_MUL=$SLAVE_NUM
      - DURATION=$DURATION
