version: '2'
services:
  master:
    image: $IMAGE
    ports:
      - 5557-5558:5557-5558
      - 8089:8089
    environment:
      - ROLE=master
      - TARGET_HOST=$TARGET_HOST
      - LOCUST_FILE_URL=$LOCUST_FILE_URL
  slave:
    image: $IMAGE
    depends_on:
      - master
    network_mode: "service:master"
    environment:
      - ROLE=slave
      - MASTER_HOST=master
      - TARGET_HOST=$TARGET_HOST
      - LOCUST_FILE_URL=$LOCUST_FILE_URL
      - SLAVE_MUL=$SLAVE_NUM
  controller:
    image: $IMAGE
    container_name: docker_locusts_controller
    depends_on:
      - master
    network_mode: "service:master"
    environment:
      - ROLE=controller
      - MASTER_HOST=master
      - AUTOMATIC=$AUTOMATIC
      - USERS=$USERS
      - HATCH_RATE=$HATCH_RATE
      - SLAVE_MUL=$SLAVE_NUM
      - DURATION=$DURATION
